config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :restaurants
  

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

  validates :name, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :phone, presence: false
  validates :website, presence: false
  validates :latitude, presence: false
  validates :longitude, presence: false

  # geocoded_by :full_street_address
  # after_validation :geocode

  # def full_street_address
  #   "#{address} #{city} #{state} #{zip}"

  # end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
#   protect_from_forgery with: :exception

  # before_filter :set_default_response_format

private
  # def set_default_response_format
  #   request.format = :html
  # end  

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def index
    @restaurants = Restaurant.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants.to_json }
    end
  end
  
  def show
    set_restaurant
    respond_to do |format|
      format.json { render json: @restaurant.to_json }
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new restaurant_params
    if @restaurant.save
      respond_to do |format|
        format.json { render json: @restaurant.to_json }
      end
  else
    respond_to do |format|
      format.json { render json: @restaurant.errors.full_messages, status: 422 }
      end
    end
  end

  def edit
    @restaurant = Restaurant.find params[:id]
  end

  def update
    @restaurant = Restaurant.find params[:id]
    if @restaurant.update_attributes restaurant_params
      respond_to do |format|
        format.json { render json: @restaurant.to_json }
      end
    else
      respond_to do |format|
        format.json { render json: @restaurant.errors.full_messages, status: 422 }
      end
    end
  end


  def destroy
    @restaurant = Restaurant.find params[:id]
    @restaurant.destroy
    respond_to do |format|
      format.json { render nothing: true }
    end
  end


  private

  def set_restaurant
    @restaurant = Restaurant.find params[:id]
  end
  
  def restaurant_params
    params.require(:restaurant).permit(
      :name,
      :address,
      :city,
      :state,
      :zip,
      :phone,
      :website,
      :latitude,
      :longitude
      )


  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dvine_Administrator</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="container">
        <div class="col-lg-12">
          <div class="row">
            <br>
            <br>
            <% if current_user %>
                  <%= link_to 'Logout', destroy_user_session_path, method: :delete =%>
                  /
                  <%= link_to 'Update Admin Info', edit_user_registration_path =%>
                  /
                  <%= link_to 'Home', root_path =%>

                  <% else %>
                  <%= link_to 'Login', new_user_session_path =%>
                  /
                  <%= link_to 'Register', new_user_registration_path =%>
                  /
                  <%= link_to 'Home', root_path =%>

                <% end %>

                <p class="notice"><%= notice %></p>
                <p class="alert"><%= alert %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <strong><%= f.label :name %></strong>
  <%= f.text_field :name %>
  <br><br>
  <strong><%= f.label :address %></strong>
  <%= f.text_field :address %>
  <br><br>
  <strong><%= f.label :city %></strong>
  <%= f.text_field :city %>
  <br><br>
    <strong><%= f.label :state %></strong>
  <%= f.text_field :state %>
  <br><br>
  <strong><%= f.label :zip %></strong>
  <%= f.text_field :zip %>
  <br><br>
  <strong><%= f.label :phone %></strong>
  <%= f.text_field :phone %>
  <br><br>
  <strong><%= f.label :website %></strong>
  <%= f.text_field :website %>
  <br><br>
  <%= f.submit %><br><br>
<% end %>

<a class="btn btn-primary btn-lg" href="<%= restaurants_path %>" role="button">Return To Restaurants Page »</a>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1 colspan="2" style="text-align:center;">
  <u>Edit Restaurant Information</u>
</h1>
<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1 colspan="2" style="text-align:center;">
  <u>Restaurants</u>
</h1>
<p id="notice">
  <%= notice %>
</p>
<br>

<div class="col-md-5">
  <a class="btn btn-primary btn-lg btn-block" href="<%= root_path %>" role="button">Home Page »</a>
  <br>
  <% @restaurants.each do |restaurant| %>
    <strong>Name:</strong>
    <%= restaurant.name %>
    <br>
    <strong>Address:</strong>
    <%= restaurant.address %>
    <br>
    <strong>City:</strong>
    <%= restaurant.city %>
    <br>
    <strong>State:</strong>
    <%= restaurant.state %>
    <br>
    <strong>Zip Code:</strong>
    <%= restaurant.zip %>
    <br>
    <strong>Phone Number:</strong>
    <%= restaurant.phone %>
    <br>
    <strong>Website:</strong>
    <%= restaurant.website %>
    <br>
    <br>
      <a class="btn btn-sm btn-info" href="<%= restaurant_path(restaurant) %>" role="button">More Information</a>
      <a class="btn btn-sm btn-warning" href="<%= edit_restaurant_path(restaurant) %>" role="button">Edit Information</a>
      <br>
      <br>
    <br>
  <% end %>
  <a class="btn btn-primary btn-lg btn-block" href="<%= new_restaurant_path %>" role="button">Enter New Restaurant »</a>
</div>

app/views/restaurants/new.html.erb
<h1>Enter New Restaurant Information</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<h1 colspan="2" style="text-align:center;">
  <u>Restaurant Information</u>
</h1>
<br>
<strong>Name:</strong>
<%= @restaurant.name %>
<br>
<strong>Address:</strong>
<%= @restaurant.address %>
<br>
<strong>City:</strong>
<%= @restaurant.city %>
<br>
<strong>State:</strong>
<%= @restaurant.state %>
<br>
<strong>Zip Code:</strong>
<%= @restaurant.zip %>
<br>
<strong>Phone Number:</strong>
<%= @restaurant.phone %>
<br>
<strong>Website:</strong>
<%= @restaurant.website %>
<br>
<br>

<%= link_to "Edit This Restaurant", edit_restaurant_path(@restaurant), class: "btn btn-warning" %>
<%= link_to "Remove This Restaurant", restaurant_path(@restaurant), method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %>
<!-- %a.btn.btn-sm.btn-primary{:href => restaurants_path, :role => "button"} List of restaurants »
-->
<%= link_to "List of Restaurants »", restaurants_path, class: "btn btn-primary" %>
<!-- %a.btn.btn-sm.btn-primary{:href => root_path, :role => "button"} Return to Home »
-->
<%= link_to "Return to Home »", root_path, class: "btn btn-primary" %>
<br>
<br>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>

app/views/welcome/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="container">
      <div class="col-lg-12">
        <div class="row">
          <h1>D'Vine Administration</h1>
          <!-- needs cancancan -->
          <br>
          <% if current_user %>
          <a class="btn btn-primary btn-lg btn-block" href="<%= restaurants_path %>" role="button">View Restaurants »</a>
          <br>
          <a class="btn btn-primary btn-lg btn-block" href="<%= new_restaurant_path %>" role="button">Enter New Restaurants »</a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>